version: '3.8'
services:
  valmarchiori:
    image: valmarchiori:latest
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    networks:
      - Singanet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.valmarchiori.rule=Host(`valmarchiori.virtuetech.com.br`)
        - traefik.http.routers.valmarchiori.entrypoints=websecure
        - traefik.http.routers.valmarchiori.tls.certresolver=letsencryptresolver
        - traefik.http.services.valmarchiori.loadbalancer.server.port=3000
        - traefik.http.services.valmarchiori.loadbalancer.passHostHeader=true
        - traefik.http.routers.valmarchiori.service=valmarchiori

networks:
  Singanet:
    external: true
