version: '3'
services:
  youlab:
    image: ghcr.io/jonathanmkt/youlab:latest
    networks:
      - Singanet
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
      - traefik.enable=1
      - traefik.http.routers.youlab.rule=Host(`youlab.com.br`)
      - traefik.http.routers.youlab.entrypoints=websecure
      - traefik.http.routers.youlab.priority=1
      - traefik.http.routers.youlab.tls.certresolver=letsencryptresolver
      - traefik.http.routers.youlab.service=youlab
      - traefik.http.services.youlab.loadbalancer.server.port=3000
      - traefik.http.services.youlab.loadbalancer.passHostHeader=true
      placement:
        constraints:
          - node.role == manager
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

networks:
  Singanet:
    external: true
