[build]
  command = "CI=false npm run build"
  publish = ".next"
  ignore_warnings = true

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_ENV = "production"
  CI = "false"
  NETLIFY_USE_YARN = "true"
  YARN_FLAGS = "--silent --no-progress"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true
